name: edw
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
# Core dependencies for Colmena
  - python==3.7.9
  - scikit-learn==0.23.2
  - redis==5.0.3
  - redis-py==3.4.1
  - sphinx
  - sphinx_rtd_theme
  - jupyterlab
  - pytest
  - flake8
  - pip

# Dependencies from the molecular design app
  - matplotlib==3.3.3
  - openbabel==3.0.0
  - geometric==0.9.*
  - qcengine==0.18.*
  - rdkit==2019.09.3
  - tensorflow==2.1.0
  - pytorch==1.*
  - cpuonly
  - qcfractal==0.14.*
  - py-cpuinfo<6
  - msgpack-python==1.*
  - mongodb==4.0.3
  - pymongo==3.11.2
  - sqlalchemy
  - xtb-python
  - psutil
  - tqdm

# Pip packages for all of them
  - pip:
      - -e .
      - parsl[monitoring]>=1.*
      - pydantic
      - python-git-info
      - gym
      - flatten-dict
      - git+https://github.com/exalearn/colmena.git
      - git+https://github.com/qmlcode/qml.git@develop
      - schnetpack==0.3.*
