name: edw
channels:
  - defaults
  - conda-forge
  - psi4/label/dev
dependencies:
# Core dependencies for Colmena
  - python==3.7.*
  - scikit-learn==0.22.*
  - redis==5.0.*
  - redis-py==3.4.*
  - sphinx
  - sphinx_rtd_theme
  - jupyterlab
  - pytest
  - flake8
  - pip

# Dependencies from the molecular design app
  - matplotlib>=3
  - openbabel==3.0.*
  - geometric==0.9.*
  - qcengine==0.17.*
  - rdkit==2019.09.3
  - tensorflow==2.1.*
  - qcfractal==0.14.*
  - psi4==1.4*
  - py-cpuinfo<6
  - msgpack-python==1.*
  - sqlalchemy
  - xtb-python
  - psutil
  - git-lfs
  - tqdm

# Pip packages for all of them
  - pip:
      - -e .
      - parsl[monitoring]>=1.*
      - pydantic
      - python-git-info
      - gym
      - git+https://github.com/exalearn/covid-drug-design.git
