# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package
defaults:
  run:
    shell: bash -l {0}

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2.0.0
      with:
        environment-file: environment.yml
        activate-environment: edw
    - name: Install dependencies
      run: |
        which python
        pip install flake8 pytest
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 moldesign
    - name: Test with pytest
      run: pytest moldesign
